新增Userec遊戲成績欄位解析及對應測試
Ptt-official-app/go-bbs pull request #41
Opened 2021-02-13 08:07 UTC by titaneric

## 📝 相關的 issue / Related Issues
- #1 

## ⛏ 變更內容 / Details of Changes

- 利用提供的欄位pos抓取bytes array上對應的欄位資訊
- 在deserialize以及serialize上都用litten endian方式抓2 bytes
- 修改testcases下.PASSWD bytes以及新增對應測試

### 測試邏輯
主要有5個遊戲類別，但只有暗棋沒有平手，所以會有3 * 5 - 1=14個欄位要被測試。
利用工具依序在這些欄位填上1到14，並同時測+16(0x10)以及+256(0x0100)以看出parsing有沒有問題

2021-02-13 13:03 UTC, PichuChen requested changes

2021-02-13 13:03 UTC, PichuChen commented on pttbbs/passwd_test.go
> +				Win:  1 + HEX16 + HEX256,
這邊放 HEX16 + HEX256 感覺會讓人混亂...

2021-02-13 13:03 UTC, PichuChen commented on pttbbs/passwd_test.go
> +	const HEX16 = 0x10
不是很清楚這邊 HEX16和 HEX256的用途

2021-02-14 04:41 UTC, titaneric commented
因新增其他欄位，還有更改某欄位位置需針對binary做大幅更動，改發另一PR，故關掉這裡

2021-02-14 04:41 UTC, closed without merging