修正 OpenFavFile err 未處理錯誤
Ptt-official-app/go-bbs pull request #74
Opened 2021-03-19 07:00 UTC by y2468101216

## 👏 解決掉的 issue / Resolved Issues
- close #39

## ⛏ 變更內容 / Details of Changes
OpenFavFile 錯誤處理
增加對 ReadUserFavoriteRecordsFile test

2021-03-19 18:36 UTC, gogog22510 commented on pttbbs/pttbbs_test.go
> +	if !strings.Contains(err.Error(), "OpenFavFile") {
我覺得比對error string不是太好的做法，可以判斷error有沒有正確return或是再多判斷return error是不是預期的error type (PS. 也可以運用go-cmp套件)

2021-03-19 18:55 UTC, PichuChen commented on pttbbs/pttbbs_test.go
> +	if !strings.Contains(err.Error(), "OpenFavFile") {
比較好的方式可能是error type, 不過目前 error handling 的部分可能接下來需要整個大改

2021-03-19 18:57 UTC, PichuChen requested changes

2021-03-19 18:57 UTC, PichuChen commented on pttbbs/pttbbs_test.go
> +	if !strings.Contains(err.Error(), "OpenFavFile") {
目前這部分在文件其實沒有定義他應該要return什麼

2021-03-19 18:57 UTC, PichuChen commented on pttbbs/pttbbs.go
> +		return nil, fmt.Errorf("pttbbs: OpenFavFile error: %v", err)
有考慮用%w嗎？

2021-03-22 01:15 UTC, y2468101216 commented on pttbbs/pttbbs.go
> +		return nil, fmt.Errorf("pttbbs: OpenFavFile error: %v", err)
是該改用%w

2021-03-22 01:15 UTC, y2468101216 commented on pttbbs/pttbbs_test.go
> +	if !strings.Contains(err.Error(), "OpenFavFile") {
所以要怎改比較好

2021-03-23 09:13 UTC, y2468101216 commented
根據討論修改了 log 方法

2021-03-23 09:50 UTC, sonorous-lester approved these changes
LGTM

2021-03-25 07:15 UTC, PichuChen approved these changes
LGTM

2021-03-25 07:15 UTC, merged