Feature/#82 do_add_recommend
Ptt-official-app/go-bbs pull request #88
Opened 2021-05-23 17:35 UTC by ChihSeanHsu

## 👏 解決掉的 issue / Resolved Issues
- close #0
- close #0

## 📝 相關的 issue / Related Issues
- #0
- #0

## ⛏ 變更內容 / Details of Changes

- xxxxxx
- xxx

2021-05-28 04:21 UTC, y2468101216 commented
請先修好 ci

2021-06-01 19:48 UTC, PichuChen commented
@ChihSeanHsu  他有發生Conflict, 不知道你那邊能幫忙處理嗎？

2021-06-01 19:53 UTC, PichuChen requested changes

2021-06-01 19:53 UTC, PichuChen commented on bbs.go
> +	DoAddRecommend(direct *string, article *ArticleRecord, ent int, buf *string, recommendType RecommendType) error
這邊的ent的意思是？ 可能需要有註解來補充

然後buf的部分應該可以直接傳入一個string而不是pointer of string?

2021-06-01 19:53 UTC, PichuChen commented on bbs.go
> +	DoAddRecommend(direct *string, article *ArticleRecord, ent int, buf *string, recommendType RecommendType) error
recommendType 也許直接傳入string比較好？

2021-06-01 19:53 UTC, PichuChen commented on filelock/filelock.go
> +	return false
這邊要加上 TODO 比較好，不然未來會有 Bug

2021-06-02 05:34 UTC, y2468101216 commented
請先解決衝突

2021-06-03 09:29 UTC, ChihSeanHsu commented on filelock/filelock.go
> +	return false
Added.

2021-06-03 09:31 UTC, ChihSeanHsu commented on bbs.go
> +	DoAddRecommend(direct *string, article *ArticleRecord, ent int, buf *string, recommendType RecommendType) error
目前這部分照在issue裡面討論到的這個function只做addNewLine，所以移掉了ent跟recommendType這兩個args，另外buf改成直接傳string了。

2021-06-03 09:33 UTC, ChihSeanHsu commented
Conflict 已經解掉了。
PTAL

另外想問一下如果想要導入`gomock`，這部分會有什麼疑慮嗎，主要是要UT有一段想要cover `IsLock`那塊的部分。

2021-06-03 10:30 UTC, PichuChen commented on pttbbs/pttbss_add_new_line.go
> +func (c *Connector) AddNewLine(
改成用append會不會比較好？

2021-06-03 10:30 UTC, PichuChen commented on pttbbs/pttbss_add_new_line.go
> +		return fmt.Errorf("DoAddRecommend: File (%s) is locked", path)
這邊函式名稱沒改到

2021-06-03 10:31 UTC, PichuChen commented on bbs.go
> +type CommonConnector interface {
comment?

2021-06-05 07:12 UTC, ChihSeanHsu commented on pttbbs/pttbss_add_new_line.go
> +func (c *Connector) AddNewLine(
Updated.

2021-06-05 07:12 UTC, ChihSeanHsu commented on pttbbs/pttbss_add_new_line.go
> +		return fmt.Errorf("DoAddRecommend: File (%s) is locked", path)
Fixed.

2021-06-05 07:14 UTC, ChihSeanHsu commented on bbs.go
> +type CommonConnector interface {
想請問這部分對於這個connector有什麼更好的命名嘛？因為想不到一個他能夠被歸納的地方，目前最理想的就是放到Article的connector

2021-06-12 18:45 UTC, PichuChen commented on bbs.go
> +type CommonConnector interface {
common 應該是「共同」的意思？ 這邊是想要表達 comment 評論嗎？

2021-06-13 08:11 UTC, ChihSeanHsu commented on bbs.go
> +type CommonConnector interface {
對，因為這部分想說未來crossPost或comment都會用到，所以他應該算是共用的function。但如果有疑慮的話就把他換回comment也是可以。

2021-06-20 09:32 UTC, ChihSeanHsu commented
Discussion on Slack with @PichuChen 
<img width="743" alt="Screen Shot 2021-06-20 at 5 29 41 PM" src="https://user-images.githubusercontent.com/34153546/122668958-7082b280-d1ed-11eb-8cb4-c8730c12145d.png">

2021-06-20 13:13 UTC, PichuChen commented on pttbbs/pttbss_append_new_line.go
> +	article.SetModified(fileStat.ModTime())
TODO: write article struct to file

2021-06-20 13:18 UTC, PichuChen approved these changes
LGTM

2021-06-20 13:20 UTC, merged